dashboard:
    path: /dashboard
    controller: DashboardController::index
pages:
    path: /dashboard/pages
    controller: PagesController::index
users:
    path: /dashboard/users
    controller: UsersController::index
settings:
    path: /dashboard/settings
    controller: SettingsController::index
comments:
    path: /dashboard/comments
    controller: CommentsController::index
