/auth:
  controller: AuthController
  action: login

/register:
  controller: AuthController
  action: register

/verif:
  controller: AuthController
  action: mailverification
/dashboard:
  controller: DashController
  action: dashboard
  security: true

/pages:
  controller: PagesController
  action: ViewPages
  security: true

/pages/add:
  controller: PagesController
  action: AddPage
  security: true

/pages/delete:
  controller: PagesController
  action: DeletePage
  security: true
  
/pages/edit:
  controller: PagesController
  action: EditPage
  security: true

/testing:
  controller: PagesController
  action: Testing

/sitemap.xml:
  controller: SitemapController
  action: ViewSitemap

/users:
  controller: UsersController
  action: ViewUsers
  security: true

/users/add:
  controller: UsersController
  action: AddUser
  security: true

/users/delete:
  controller: UsersController
  action: DeleteUser
  security: true

/users/edit:
  controller: UsersController
  action: EditUser
  security: true