/:
  controller: FrontController
  action: home
  security: false
/{slug}:
  controller: FrontController
  action: index
  security: false

/bdfy-admin/login:
  controller: AuthController
  action: login
  security: false

/bdfy-admin/register:
  controller: AuthController
  action: register
  security: false

/bdfy-admin/verif:
  controller: AuthController
  action: mailverification
  security: false

/bdfy-admin/dashboard:
  controller: DashController
  action: dashboard
  security: true

/bdfy-admin/pages:
  controller: PagesController
  action: ViewPages
  security: true

/bdfy-admin/pages/add:
  controller: PagesController
  action: AddPage
  security: true

/bdfy-admin/pages/delete:
  controller: PagesController
  action: DeletePage
  security: true
/bdfy-admin/pages/edit:
  controller: PagesController
  action: EditPage
  security: true

/bdfy-admin/pages/view:
  controller: PagesController
  action: ViewPage
  security: true

/bdfy-admin/pages/history:
  controller: PagesController
  action: ViewHistory
  security: true

/bdfy-admin/pages/history/apply:
  controller: PagesController
  action: ApplyHistory
  security: true

/bdfy-admin/menus:
  controller: MenuController
  action: ViewMenus
  security: true
/bdfy-admin/menus/add:
  controller: MenuController
  action: CreateMenu
  security: true
/bdfy-admin/menu/edit:
  controller: MenuController
  action: EditMenu
  security: true
/bdfy-admin/menu/delete:
  controller: MenuController
  action: DeleteMenu
  security: true

/bdfy-admin/sitemap.xml:
  controller: SitemapController
  action: ViewSitemap
  security: true

/bdfy-admin/users:
  controller: UsersController
  action: ViewUsers
  security: true
  role: admin

/bdfy-admin/users/add:
  controller: UsersController
  action: AddUser
  security: true
  role: admin

/bdfy-admin/users/delete:
  controller: UsersController
  action: DeleteUser
  security: true
  role: admin

/bdfy-admin/users/edit:
  controller: UsersController
  action: EditUser
  security: true
  role: admin

/bdfy-admin/logout:
  controller: AuthController
  action: logout
  security: false

/404/not_found:
  controller: ErrorController
  action: NotFound
  security: false

/403/access_denied:
  controller: ErrorController
  action: AccessDenied
  security: true

/bdfy-admin/comments:
  controller: CommentsController
  action: getAllComments
  security: true 


/bdfy-admin/comments/add:
  controller: CommentsController
  action: addComment
  security: true

/bdfy-admin/comments/delete:
  controller: CommentsController
  action: DeleteComment
  security: true
  role: admin


/bdfy-admin/comments/edit:
  controller: CommentsController
  action: EditComment
  security: true

/bdfy-admin/comments/report:
  controller: CommentsController
  action: report
  security : true
  role: admin

/bdfy-admin/articles:
  controller: ArticleController
  action: ViewArticles
  security: true

/bdfy-admin/articles/add:
  controller: ArticleController
  action: AddArticle
  security: true

/bdfy-admin/articles/delete:
  controller: ArticleController
  action: DeleteArticle
  security: true

/bdfy-admin/articles/edit:
  controller: ArticleController
  action: EditArticle
  security: true

/article/singlearticle:
  controller: ArticleController
  action: ViewSingleArticle
  security: false

/bdfy-admin/categories:
  controller: CategorieController
  action: ViewCategories
  security: true

/bdfy-admin/categories/add:
  controller: CategorieController
  action: AddCategorie
  security: true

/bdfy-admin/categories/delete:
  controller: CategorieController
  action: DeleteCategorie
  security: true
  
/bdfy-admin/categories/edit:
  controller: CategorieController
  action: EditCategorie
  security: true
/installer/db:
  controller: InstallerController
  action: setup
  security: false
/installer/launch:
  controller: InstallerController
  action: launchInstaller
  security: false
